Repository AY2324S2-CS2103T-T17-3/tp, pull requests merged in 2024-04, with the labels that each got.

#174 Feature: Add weight feature with history tracking, and height feature
  .github/workflows/gradle.yml
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/WeightCommand.java
  src/main/java/seedu/address/logic/messages/AddCommandMessages.java
  src/main/java/seedu/address/logic/messages/EditCommandMessages.java
  src/main/java/seedu/address/logic/messages/FindCommandMessages.java
  src/main/java/seedu/address/logic/messages/Messages.java
  src/main/java/seedu/address/logic/messages/WeightCommandMessages.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/WeightCommandParser.java
  src/main/java/seedu/address/model/person/Height.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/predicates/HeightContainsRangePredicate.java
  src/main/java/seedu/address/model/person/predicates/WeightMapContainsWeightRangePredicate.java
  src/main/java/seedu/address/model/person/weight/Weight.java
  src/main/java/seedu/address/model/person/weight/WeightEntry.java
  src/main/java/seedu/address/model/person/weight/WeightMap.java
  src/main/java/seedu/address/model/tag/TagSet.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedWeight.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonDetailsPanel.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/WeightCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/WeightCommandParserTest.java
  src/test/java/seedu/address/model/person/HeightTest.java
  src/test/java/seedu/address/model/person/WeightMapTest.java
  src/test/java/seedu/address/model/person/WeightTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#218 Fix details view cleared on first command
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bug, priority.Medium

#216 Update QR generation sequence diagram
  docs/diagrams/QrAddPersonSequenceDiagram.puml
  docs/images/QrAddPersonSequenceDiagram.png
Labels: type.Bug, type.Docs

#226 Extension: Note editing
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/NoteEditCommand.java
  src/main/java/seedu/address/logic/messages/NoteCommandMessages.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
Labels: type.Enhancement, priority.Medium

#225 Bug: Fix Date
  src/main/java/seedu/address/commons/util/DateTimeUtil.java
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
Labels: type.Bug, priority.Medium, severity.Medium

#230 Task: Hide height label if empty
  src/main/java/seedu/address/model/person/Height.java
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
Labels: type.Task, priority.Medium

#237 Update user guide
  docs/UserGuide.md
Labels: priority.High, type.Docs

#245 Docs - Change typo in Find command in UG
  docs/UserGuide.md
Labels: priority.High, type.Docs

#302 Bug: Fix find command incorrectly parsing empty attributes (find w/ h/)
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/Height.java
  src/main/java/seedu/address/model/person/predicates/SearchPredicate.java
  src/main/java/seedu/address/model/person/predicates/TagSetContainsAllTagsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, priority.Medium

#304 Docs - Update DG (Week 10 tasks) (Gopi)
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Docs

#307 Add planned enhancement for weight and more specific error messages for optional fields
  docs/DeveloperGuide.md
Labels: priority.High, response.PlannedEnhancement

#308 Limit height and weight values to 5000
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/WeightCommand.java
  src/main/java/seedu/address/model/person/Height.java
  src/main/java/seedu/address/model/person/weight/Weight.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/WeightCommandParserTest.java
Labels: priority.High, response.WillFix

#309 Docs: Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/WeightCommandActivityDiagram.puml
  docs/images/WeightCommandActivityDiagram.png
Labels: priority.High

#310 Update UG to include '0' values for height/weight
  docs/UserGuide.md
Labels: priority.High, response.WillFix

#311 Include hyperlinks in command summary
  docs/UserGuide.md
Labels: priority.High, response.WillFix

#312 Account for extraneous weight and height in UG
  docs/UserGuide.md
Labels: priority.High, response.WillFix

#314 Add too dense QR code problem to known issues
  docs/UserGuide.md
Labels: type.Docs

#338 Fix exception message
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: priority.High

#326 Fix invalid JSON data parsing
  src/main/java/seedu/address/model/person/Height.java
  src/main/java/seedu/address/model/person/weight/Weight.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedWeight.java
Labels: priority.High, response.WillFix

#337 Add overwriting of exercise values
  src/main/java/seedu/address/logic/commands/FitAddCommand.java
  src/main/java/seedu/address/logic/parser/FitAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/exercise/Exercise.java
  src/main/java/seedu/address/model/exercise/ExerciseToAdd.java
  src/test/java/seedu/address/logic/commands/FitAddCommandTest.java
  src/test/java/seedu/address/logic/commands/FitDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/FitAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FitDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/ExerciseTest.java
Labels: type.Bug, priority.High, severity.High

#346 Remove redundant constructor
  src/main/java/seedu/address/logic/commands/WeightCommand.java
Labels: priority.High

#347 Docs: Update find command details in DG
  docs/DeveloperGuide.md
Labels: type.Docs

#358 Docs: Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddNoteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AddNoteSequenceDiagram.png
  docs/images/CorruptingDataAfter.png
  docs/images/CorruptingDataBefore.png
  docs/images/ModelClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Docs

#360 Update user stories
  docs/DeveloperGuide.md
Labels: priority.High

#362 Add non-alnum names to planned enhancements
  docs/DeveloperGuide.md
Labels: type.Docs

#365 Update JavaDoc comments
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/WeightCommand.java
  src/main/java/seedu/address/logic/messages/AddCommandMessages.java
  src/main/java/seedu/address/logic/messages/EditCommandMessages.java
  src/main/java/seedu/address/logic/messages/FindCommandMessages.java
  src/main/java/seedu/address/logic/messages/Messages.java
  src/main/java/seedu/address/logic/messages/WeightCommandMessages.java
  src/main/java/seedu/address/model/person/Height.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/weight/Weight.java
  src/main/java/seedu/address/model/person/weight/WeightEntry.java
  src/main/java/seedu/address/model/person/weight/WeightMap.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedWeight.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High

#369 Update use cases for `height` and `weight`
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/messages/WeightMessages.java
  src/main/java/seedu/address/model/person/weight/Weight.java
Labels: priority.High

#375 Fix typos and formatting
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/messages/WeightMessages.java
  src/main/java/seedu/address/model/person/weight/Weight.java
Labels: priority.High

#376 Docs: Fix formatting and phrasing issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High
