Repository AY2324S2-CS2103T-T17-3/tp, pull requests merged in 2024-03, with the labels that each got.

#18 Update user stories for developer guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Docs

#19 Update User Stories in the Developer Guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Docs

#16 Update README
  README.md
  docs/images/Ui.png
Labels: priority.High, type.Docs

#23 Update site-wide settings
  .gitignore
  docs/_config.yml
Labels: priority.High, type.Docs

#29 Fix _config.yml theme
  docs/_config.yml
Labels: priority.High, type.Docs

#30 Update roles and responsibilities in AboutUs page - Ryan
  docs/AboutUs.md
  docs/images/ryanngwh.png
Labels: priority.High, type.Docs

#34 Update User Guide and Index page
  docs/UserGuide.md
  docs/index.md
Labels: type.Docs

#46 Update NFR in develop guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Docs

#48 Update product name in entire project
  README.md
  docs/AboutUs.md
  docs/UserGuide.md
  docs/_config.yml
  docs/index.md
Labels: priority.High, type.Docs

#50 Update README
  README.md
Labels: priority.High, type.Docs

#39 Update glossary in developer guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Docs

#61 Remove duplicate user story
  docs/DeveloperGuide.md
Labels: priority.High, type.Docs

#64 Add Command Help to Help Menu
  docs/DeveloperGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Story, priority.High

#65 Add confirmation for clear command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Enhancement, priority.Medium

#66 Implement note feature
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Story, priority.High

#68 Add user story for help menu
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Docs

#73 Update Docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
Labels: priority.Low, type.Docs

#72 Update delete
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: type.Task, priority.High

#79 Implement detection of duplicate note prefixes in add command
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: type.Bug, priority.Medium

#74 Feature mandatory fields
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: type.Story, priority.High

#71 Add QR Code for Contacts
  build.gradle
  docs/DeveloperGuide.md
  src/main/java/seedu/address/QrCodeGenerator.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/QrCodeGeneratorTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Story, priority.Medium

#85 Fix bug for edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Bug, priority.Medium

#83 Update EditCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, priority.Low

#82 Add QR Code Generation Info to Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/QRGenerationActivityDiagram.puml
  docs/images/QRGenerationActivityDiagram.png
  src/main/java/seedu/address/QrCodeGenerator.java
Labels: priority.High, type.Docs

#93 Update note feature in user guide
  docs/UserGuide.md
Labels: priority.Medium, type.Docs

#99 Add QR Code Section to User Guide
  docs/UserGuide.md
  docs/images/QRContact.png
  docs/images/QRScanning.png
  docs/images/QrCodeContactCard.png
Labels: priority.Medium, type.Docs

#97 Update note prefix duplication test cases and checks
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
Labels: type.Task, priority.Medium

#103 Bugfix: Update phone validation
  .gitignore
  src/main/java/seedu/address/model/person/Phone.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, priority.High

#100 Bugfix: Update duplicate client check
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Bug, priority.High

#102 Fix QR Code Generation and Deletion
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Bug, severity.Medium

#109 BugFix: Help window formatting
  src/main/java/seedu/address/commons/util/AppUtil.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Bug, priority.Medium, severity.VeryLow

#108 Add Acknowledgement for QR Code Library & Table of Contents
  docs/DeveloperGuide.md
  docs/index.md
Labels: priority.Medium, type.Docs

#116 Add sequence diagram and update note command in DG
  docs/DeveloperGuide.md
  docs/diagrams/AddNoteSequenceDiagram.puml
  docs/images/AddNoteSequenceDiagram.png
Labels: priority.Medium, type.Docs

#118 Fix minor typo in sequence diagram
  docs/diagrams/AddNoteSequenceDiagram.puml
Labels: severity.Low, type.Docs

#119 Rename built jar file to FitBook
  build.gradle
Labels: type.Task, priority.Medium

#136 Bugfix: Edge case causing QR not to generate
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bug, priority.Medium, severity.Medium

#130 Remove deprecated NameContainsKeywordsPredicate
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicateTest.java
Labels: type.Task, priority.Low

#132 Add test cases for Note
  src/main/java/seedu/address/model/person/Note.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NoteTest.java
Labels: type.Task, priority.Medium

#141 Task: Add backwards compatibility for new note field
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: type.Task, priority.Medium, severity.Medium

#142 Docs: Add/update UML diagram for add/edit contact details
  docs/DeveloperGuide.md
  docs/diagrams/AddEditCommandActivityDiagram.puml
  docs/images/AddAndEditCommandActivityDiagram.png
Labels: priority.Medium, type.Docs

#134 Enhancement: Improve phone number input readability
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Attribute.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: type.Enhancement, priority.Low, severity.Low

#129 Task: Update help window formatting
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task, priority.Medium

#144 Update sequence diagram for Note
  docs/diagrams/AddNoteSequenceDiagram.puml
  docs/images/AddNoteSequenceDiagram.png
Labels: priority.Low, type.Docs

#138 Enhancement: Improved how results are displayed
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.Medium

#151 Bug: Remove extra square brackets around tags
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Bug, priority.Low, severity.VeryLow

#153 Task: Abstract out generation of Person string
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
Labels: type.Task, priority.Medium

#154 Task: Enable assertions for run configuration in build.gradle
  build.gradle
Labels: type.Task, priority.High

#128 Task: Update UI to Match Mockup
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetailsPanel.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task, priority.High

#157 Task: Use assertion in QR code generation
  src/main/java/seedu/address/logic/QrCodeGenerator.java
Labels: type.Task, priority.High

#143 Docs: Add Find Command Implementation Details
  docs/DeveloperGuide.md
  docs/diagrams/FindCommandSequenceDiagram-Logic.puml
  docs/images/FindCommandSequenceDiagram-Logic.png
Labels: priority.Medium, type.Docs

#165 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/AddNoteSequenceDiagram.puml
  docs/images/AddNoteSequenceDiagram.png
Labels: priority.High, type.Docs

#172 Update Note prefix
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddNoteSequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: type.Task, priority.Medium

#170 Update UG based on CS2101 feedback
  docs/UserGuide.md
Labels: priority.High, type.Docs

#166 Add email, address and note to QR code
  src/main/java/seedu/address/logic/QrCodeGenerator.java
Labels: type.Enhancement, priority.Medium

#164 Bug: Fix inconsistent error messages
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
Labels: type.Bug, priority.Medium

#178 Enhancement: Vertically aligns person list
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, priority.Low

#182 Bug: Fix exit command
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.Medium, severity.Medium

#197 Task: Remove unused assets
  docs/images/findAlexDavidResult.png
  docs/images/johndoe.png
Labels: type.Task, priority.Medium, severity.Low

#192 Update user guide
  docs/UserGuide.md
Labels: priority.High, type.Docs

#200 Enhancement: Remove required prefix in note command
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#204 Fix generation of QR codes for long names
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/QrCodeGenerator.java
  src/test/java/seedu/address/QrCodeGeneratorTest.java
Labels: type.Bug, severity.Medium

#198 Bugfix: Tag substring matching
  .github/workflows/gradle.yml
  config/markdown-link-check_config.json
  docs/UserGuide.md
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/TagSet.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/tag/TagSetTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#189 Bug: Fix result messages
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, priority.Low

#210 Task: Create message classes to improve code quality for command classes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/messages/AddCommandMessages.java
  src/main/java/seedu/address/logic/messages/ClearCommandMessages.java
  src/main/java/seedu/address/logic/messages/DeleteCommandMessages.java
  src/main/java/seedu/address/logic/messages/EditCommandMessages.java
  src/main/java/seedu/address/logic/messages/ExitCommandMessages.java
  src/main/java/seedu/address/logic/messages/FindCommandMessages.java
  src/main/java/seedu/address/logic/messages/HelpCommandMessages.java
  src/main/java/seedu/address/logic/messages/ListCommandMessages.java
  src/main/java/seedu/address/logic/messages/Messages.java
  src/main/java/seedu/address/logic/messages/NoteCommandMessages.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.Medium
